# Generated by Django 5.1.7 on 2025-04-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_postauthor_blogpost_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Опубликовать"),
        ),
    ]
